### PR TITLE
feat(RelatedPanes) add related panes functionality CSS

### PR DESCRIPTION
**Pull request by joebordes**

### CODE REVIEW

**Comment by Luke1982** [comment]
I accepted this pull, but what exactly is the related panes functionality?

**Comment by joebordes** [comment]
We can now add "tabs" or "panes" like the "more information" tab on any module. You can define a title for the tab and then what blocks you want to be shown when the user clicks on the tab.
There are 3/4 types of blocks that you can put inside any tab in any order

http://corebos.org/documentation/doku.php?id=en:adminmanual:businessmappings:relatedpanes

**Comment by joebordes** [comment]
something like this:
http://discussions.corebos.org/attachment.php?aid=50
discussions.corebos.org/thread-218.html

**Comment by Luke1982** [comment]
Cool, and a lot better UI wise than the related lists.

**Comment by Luke1982** [comment]
I saw a couple of commits in the master but haven't really taken the time to research..

**Pull request merged**
